version: '3.8'

services:
  login:
    build: ./login
    container_name: micro-login
    ports:
      - "8080:8080"
      
  pedidos:
    build: ./pedidos
    container_name: micro-pedidos
    ports:
      - "8081:8081"
